apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-0
  labels:
    type: local
    app: kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/kafka-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-1
  labels:
    type: local
    app: kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/kafka-data-2
  persistentVolumeReclaimPolicy: Recycle
---

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-2
  labels:
    type: local
    app: kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/kafka-data-3
  persistentVolumeReclaimPolicy: Recycle
