apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-0
  labels:
    type: local
    app: zk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/zk-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-1
  labels:
    type: local
    app: zk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/zk-data-2
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-2
  labels:
    type: local
    app: zk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/zk-data-3
  persistentVolumeReclaimPolicy: Recycle
